language: node_js
node_js:
  - stable
script:
  - echo 'Installing dependencies'
  - npm install
  - echo 'Running tests'
  - npm test
deploy:
  provider: heroku
  api_key: $api_key
  app: trungtextanalyzer
  on:
    branch: main